### ISSUE TITLE
File name extension lost when using fileNameFunction for the first uploaded file

### ISSUE THREAD

**Issue by zkMake** [webtechnick/CakePHP-FileUpload-Plugin#1]
I'm using the fileNameFunction feature to generate a SHA-1 hash of the file name, but the problem is that when you upload a file for the first time and the hash generates a unique value some how the extension of the file is lost and the file which is saved has no extension.

The problem seems to be at line number 90 in the "uploader.php" file under the "vendors" folder.

return $fileName . $this->_ext();
instead of 
return $fileName;

**Comment by webtechnick** [comment]
Indeed this is an issue when using sha1 or any of the other built in php fuctions.  It's not as simple as that however, because that only makes sense to add the ext() if we're using a sha1 or md5 hash algorithm.   A normal upload would end up returning file.jpg.jpg, which is not ideal.   

A work around is to define your own function, and then append the extension after the sha1.

I will file this as a bug, and fix it in the next release.

Thank you for bringing it to my attention.

**Comment by Reen** [comment]
Instead of adding the extension to the filename it would be nice to be able to save the original filename to the database as well.
I'm using private downloads (i.e. my files are in app/tmp/files) and would serve the files with the correct mime type as well as original filename, but like the files to be saved by sha-filenames. Therefore I need an extra entry for the "fields" parameter that holds the original filename.

Thanks for this great plugin.
